### ISSUE TITLE
Images have different sizes

### ISSUE THREAD

**Issue by blackvvine** [backflip/puppeteer-speedline#1]
Hi, I am trying to run the project on Arch Linux with Node v11.15.0, and I run into this error:
```
Error: Images have different sizes!
    at Object.compare (/home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/image-ssim/index.js:38:19)
    at calculateFrameSimilarity (/home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/speedline/src/speed-index.js:126:25)
    at Object.calculatePerceptualProgress (/home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/speedline/src/speed-index.js:133:28)
    at /home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/speedline/src/index.js:51:15
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
```

Any help would be appreciated.

**Comment by mark1145588963** [comment]
I have the same problem.Did you resolve it ?

**Comment by mark1145588963** [comment]
> Hi, I am trying to run the project on Arch Linux with Node v11.15.0, and I run into this error:
> 
> ```
> Error: Images have different sizes!
>     at Object.compare (/home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/image-ssim/index.js:38:19)
>     at calculateFrameSimilarity (/home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/speedline/src/speed-index.js:126:25)
>     at Object.calculatePerceptualProgress (/home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/speedline/src/speed-index.js:133:28)
>     at /home/blackvvine/Workspace/Simorgh/puppeteer-speedline/node_modules/speedline/src/index.js:51:15
>     at processTicksAndRejections (internal/process/task_queues.js:86:5)
> ```
> 
> Any help would be appreciated.

I have the same problem.Did you resolve it ?
